run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - revive
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    # Replaces structcheck and varcheck.
    - unused
    - unparam

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 25
  golint:
    min-confidence: 0.85
