// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.

package codegen

import (
	"bytes"
	"context"
	"fmt"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
